{
 "title": "Story Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "cometbft" }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(${namespace}_consensus_latest_block_height{chain_id=\"iliad-0\"})",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${namespace}_consensus_total_txs{chain_id=\"iliad-0\"}",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Block / min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(${namespace}_consensus_latest_block_height{chain_id=\"iliad-0\"}[10m])) / 10",
     "legendFormat": "Verbose"
    }
   ]
  },
  {
   "title": "Bonded Token",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${namespace}_consensus_validators_power{chain_id=\"iliad-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "${namespace}_p2p_peers{chain_id=\"iliad-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${namespace}_mempool_size{chain_id=\"iliad-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "${namespace}_consensus_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Validators"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "${namespace}_consensus_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "${namespace}_consensus_missing_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Block Missed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "${namespace}_consensus_missing_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "${namespace}_consensus_block_size_bytes{chain_id=\"iliad-0\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "${namespace}_consensus_num_txs{chain_id=\"iliad-0\"}",
     "legendFormat": "Block Size"
    }
   ]
  }
 ]
}